### ISSUE TITLE
Data transfer by ownership, progress messages, premature cancel

### ISSUE THREAD

**Issue by amergin** [keithwhor/multithread.js#5]
A few questions about the library if you don't mind:
- how is the data transferred to the threads: is it copied or transferred by `transfer-by-ownership`?
- any way to easily include external functions, external libraries, global constants to each thread?
- any way to terminate threads prematurely (allowing user to cancel pending computation)?
- any way to get progress messages from the threads (so progress bars and other UI indicators can be shown)?
- any chance to control the threads in sync using promises. That is, 
  - provide an array of, say, 30 objects that each contain the necessary data for each thread to do its calculation
  - start the maximum number of threads the client can handle (for instance start 8 threads and form a queue for 22)
  - when all threads complete, resolve a promise or reject it depending on possible raised exceptions during computation.
  - allow the before-mentioned features to be used in this synchronized batch job.

**Comment by keithwhor** [comment]
- Data is transferred using [transferable object](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Passing_data_by_transferring_ownership_(transferable_objects) (`transfer-by-ownership`).
- No, worker threads have their own execution context. If you need to do heavy lifting out of the scope of this project, I recommend getting down to the metal and writing workers yourself as separate scripts.
- As for everything else, not in the scope of this project.

All of the granularity you're asking about can just be done [using web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers), which this library provides a wrapper for. Check 'em out.

**Comment by mathiasrw** [comment]
@amergin

> - provide an array of, say, 30 objects that each contain the necessary data for each thread to do its calculation
> - start the maximum number of threads the client can handle (for instance start 8 threads and form a queue for 22)
> - when all threads complete, resolve a promise or reject it depending on possible raised exceptions during computation.

Have a look at http://parallel.js.org
