### ISSUE TITLE
Support transferable objects

### ISSUE THREAD

**Issue by letmaik** [keithwhor/multithread.js#7]
It would be great if this library could support [transferable objects](https://developers.google.com/web/updates/2011/12/Transferable-Objects-Lightning-Fast) for high performance cases where it would be bad to serialize a huge typed array as JSON for example.

**Comment by keithwhor** [comment]
Hey! Thanks for your interest.

It does support transferable objects --- MT.processInt32() and MT.processFloat64() exist for this reason.

**Comment by letmaik** [comment]
Hm, are you sure? The examples don't show this case. I mean for example transferring a [Float64Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array) instance without making a copy.
