### ISSUE TITLE
Syntax?

### ISSUE THREAD

**Issue by amilajack** [keithwhor/multithread.js#8]
@keithwhor  Never seen this kind of syntax before:

https://github.com/keithwhor/multithread.js/blob/master/multithread.js#L26

What does the `/**/` mean in an variable declaration?

**Comment by amilajack** [comment]
Also what does the self refer to here:

https://github.com/keithwhor/multithread.js/blob/master/multithread.js#L27

**Comment by keithwhor** [comment]
This function is stringified and used as a boilerplate to create a web worker. The comments `/**/` are for easy regex string replacement.

`self` refers to the worker that's created around the function.
