### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by amilajack** [keithwhor/multithread.js#9]
I am willing to offer long term and active support for this project if that is fine with you.

I'm considering:
- Refactoring
- Offering test coverage
- Providing support for modern node versions
- Improving performance

**Comment by keithwhor** [comment]
Yeah no problem! I've been super busy with https://github.com/keithwhor/nodal. If you want to submit some PRs to let me know what you're thinking I'm happy to take a look. If it's all good, happy to give you full access to the repo.

**Comment by amilajack** [comment]
Thanks! Expect some PR's soon :)

**Comment by amilajack** [comment]
Also when refactoring, I came across some syntax that I didn't think was valid: https://github.com/keithwhor/multithread.js/issues/8
